version: "3.9"

services:
  project-name:
    container_name: project_name_app
    image: everybody8/project-name:v1.0
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      postgresdb:
        condition: service_healthy
    networks:
      - sql_net

  postgresdb:
    image: postgres:latest
    container_name: postgres_container
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DBNAME}
      - DATABASE_HOST=${POSTGRES_HOST}
    ports:
      - "5433:5432"
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USERNAME} -d ${POSTGRES_DBNAME}'"]
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - sql_net

# Networks to be created to facilitate communication between containers
networks:
  sql_net:
    driver: bridge

volumes:
  database:
  app:
